FROM node:20-alpine AS deps
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && corepack prepare pnpm@8.15.8 --activate && pnpm i --frozen-lockfile

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# 声明构建参数
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SHOW_CUSTOM_AD
ARG NEXT_PUBLIC_ASSETS_URL
ARG NEXT_PUBLIC_GOOGLE_ID
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_SRC
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_DOC_SEARCH_APP_ID
ARG NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME
ARG NEXT_PUBLIC_DOC_SEARCH_API_KEY
ARG RESEND_API_KEY
ARG ADMIN_EMAIL
ARG RESEND_AUDIENCE_ID
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY
ARG DAY_MAX_SUBMISSIONS

# 设置为环境变量，使应用能够访问
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_SHOW_CUSTOM_AD=${NEXT_PUBLIC_SHOW_CUSTOM_AD}
ENV NEXT_PUBLIC_ASSETS_URL=${NEXT_PUBLIC_ASSETS_URL}
ENV NEXT_PUBLIC_GOOGLE_ID=${NEXT_PUBLIC_GOOGLE_ID}
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
ENV NEXT_PUBLIC_PLAUSIBLE_SRC=${NEXT_PUBLIC_PLAUSIBLE_SRC}
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_ID=${NEXT_PUBLIC_GOOGLE_ADSENSE_ID}
ENV NEXT_PUBLIC_DOC_SEARCH_APP_ID=${NEXT_PUBLIC_DOC_SEARCH_APP_ID}
ENV NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME=${NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME}
ENV NEXT_PUBLIC_DOC_SEARCH_API_KEY=${NEXT_PUBLIC_DOC_SEARCH_API_KEY}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}
ENV RESEND_AUDIENCE_ID=${RESEND_AUDIENCE_ID}
ENV UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
ENV UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
ENV UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY=${UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY}
ENV DAY_MAX_SUBMISSIONS=${DAY_MAX_SUBMISSIONS}

ENV NEXT_TELEMETRY_DISABLED 1

RUN corepack enable && corepack prepare pnpm@8.15.8 --activate && pnpm build

# Production image, copy all the files and run next
FROM node:20-alpine AS runner
WORKDIR /app

# 声明构建参数
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SHOW_CUSTOM_AD
ARG NEXT_PUBLIC_ASSETS_URL
ARG NEXT_PUBLIC_GOOGLE_ID
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_SRC
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_DOC_SEARCH_APP_ID
ARG NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME
ARG NEXT_PUBLIC_DOC_SEARCH_API_KEY
ARG RESEND_API_KEY
ARG ADMIN_EMAIL
ARG RESEND_AUDIENCE_ID
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY
ARG DAY_MAX_SUBMISSIONS

# 设置为环境变量，使应用能够访问
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_SHOW_CUSTOM_AD=${NEXT_PUBLIC_SHOW_CUSTOM_AD}
ENV NEXT_PUBLIC_ASSETS_URL=${NEXT_PUBLIC_ASSETS_URL}
ENV NEXT_PUBLIC_GOOGLE_ID=${NEXT_PUBLIC_GOOGLE_ID}
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
ENV NEXT_PUBLIC_PLAUSIBLE_SRC=${NEXT_PUBLIC_PLAUSIBLE_SRC}
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_ID=${NEXT_PUBLIC_GOOGLE_ADSENSE_ID}
ENV NEXT_PUBLIC_DOC_SEARCH_APP_ID=${NEXT_PUBLIC_DOC_SEARCH_APP_ID}
ENV NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME=${NEXT_PUBLIC_DOC_SEARCH_INDEX_NAME}
ENV NEXT_PUBLIC_DOC_SEARCH_API_KEY=${NEXT_PUBLIC_DOC_SEARCH_API_KEY}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}
ENV RESEND_AUDIENCE_ID=${RESEND_AUDIENCE_ID}
ENV UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
ENV UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
ENV UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY=${UPSTASH_REDIS_NEWSLETTER_RATE_LIMIT_KEY}
ENV DAY_MAX_SUBMISSIONS=${DAY_MAX_SUBMISSIONS}

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]